routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


//
Auth::routes();
//Auth::loginUsingId(1);
Route::group(['middleware' => 'auth'], function() {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/', function(){
        return redirect('home');
    })->name('home');
    /*permissions*/
    Route::resource('permissions', 'PermissionController');
    Route::get('permissions-datatable', 'PermissionController@permissionDatatable')->name('permissions.datatable');

    /*roles*/
    Route::resource('roles', 'RoleController');
    Route::get('roles-datatable', 'RoleController@roleDatatable')->name('roles.datatable');

    /*users*/
    Route::resource('users', 'UserController');
    Route::DELETE('users-enabled/{user}', 'UserController@userEnabled')->name('users.enabled');
    Route::get('users-datatable', 'UserController@usersDatatable')->name('users.datatable');
    Route::get('my-profile', 'UserController@myProfile')->name('my.profile');
    Route::post('my-profile-update', 'UserController@updateMyProfile')->name('my.profile.update');
//    Route::get('users-profile/{user}', 'UserController@usersDatatable')->name('users.profile');
});

app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Role extends \Spatie\Permission\Models\Role
{
    protected $casts = [
        'created_at' => 'datetime:M d, Y h:i:s a',
    ];
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Permission;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use Spatie\Permission\Models\Role;
use Yajra\DataTables\Facades\DataTables;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
//        if (! Gate::allows('role_view')) {
//            return abort(403);
//        }
        return view('app.pages.roles.index');
    }

    public function roleDatatable(){
        if (! Gate::allows('role_view')) {
            return abort(403);
        }
        $data = \App\Role::query();
        return DataTables::of($data)
            ->addColumn('permissions',function ($data){
                $permissions = $data->permissions()->pluck('name');
                $html='';
                if(count($permissions)>0){
                    foreach($permissions as $permission) {
                        $html .= ' <span class="badge badge-primary">' . $permission . '</span>';
                    }
                }else{
                    $html.='<p>No Permission</p>';
                }

                return $html;
            })
            ->addColumn('action', function ($data) {
                $html='<a class="btn btn-sm btn-warning btn-icon btn-icon-md" title="Edit" href="" type="button" data-btn="edit" data-id="'.$data->id.'" data-toggle="modal" data-target="#modal-lg">
                       <i class="la la-edit"></i>
                        </a>';
                $html.='<a href="" class="btn btn-sm btn-danger btn-icon btn-icon-md" title="Delete"  type="button" data-btn="delete" data-id="'.$data->id.'" data-toggle="modal" data-target="#modal-lg-delete">
                        <i class="la la-trash"></i>
                        </a>';
                return  $html;
            })
            ->rawColumns(['action','permissions'])
            ->toArray();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (! Gate::allows('role_create')) {
            return abort(403);
        }
        $permissions = Permission::all();
        //render form
        $form = view()->make('app.pages.roles._form',compact('permissions'))->render();
        //save to variable
        $data = array(
            'form' => $form,
        );
        //return json
        return response()->json($data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if (! Gate::allows('role_create')) {
            return abort(403);
        }

        $request->validate([
            'name' => 'required|unique:roles,name|regex:/(^[A-Za-z0-9-_]+$)+/',
            'permissions'=>'required'
        ]);
        $role = Role::create($request->except('permissions'));
        $permissions = $request->input('permissions') ? $request->input('permissions') : [];
        $role->givePermissionTo($permissions);
        if($role){
            return  response()->json([
                'status'=>'success',
                'message'=>'Role Successfully Added'
            ]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (! Gate::allows('role_update')) {
            return abort(403);
        }
        $permissions = Permission::all();
        $role = Role::findOrFail($id);
        $form = view()->make('app.pages.roles._form',compact('permissions','role'))->render();
        //save to variable
        $data = array(
            'form' => $form,
        );
        //return json
        return response()->json($data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if (! Gate::allows('role_update')) {
            return abort(403);
        }
        $request->validate([
            'name' => 'required|unique:roles,name,'.$request->role.'|regex:/(^[A-Za-z0-9-_]+$)+/',
            'permissions'=>'required'
        ]);

        $role = Role::findOrFail($id);
        $role->update($request->except('permissions'));
        $permissions = $request->input('permissions') ? $request->input('permissions') : [];
        $role->syncPermissions($permissions);

        if($role){
            return  response()->json([
                'status'=>'success',
                'message'=>'Role Successfully Updated'
            ]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (! Gate::allows('role_delete')) {
            return abort(403);
        }
        $role = Role::findOrFail($id);
        $role->delete();

        if($role){
            return  response()->json([
                'status'=>'success',
                'message'=>'Role Successfully Deleted',
            ]);
        }
    }
}

resources/views/app/pages/roles/_form.blade.php
<form id="form" class="kt-form">
    @csrf
    @isset($role)
        {{ method_field('PUT') }}
    @endisset
    <div class="form-group">
        <label>Role Name <span class="required">*</span>
        </label>
            <input type="text" name="name" required="required" value="{{$role->name ?? ''}}" class="form-control">
    </div>
    <div class="form-group">
        <label>Select Permission <span class="required">*</span>
            <br>
            <small class="text-navy">Role can have 1 or more permissions</small>
        </label>
        <div class="kt-checkbox-inline">
            @forelse($permissions as $key=>$permission)
                @if(isset($role))
                    <label class="kt-checkbox">
                        <input type="checkbox" name="permissions[]" value="{{$permission->name}}"
                               @foreach($role->permissions()->pluck('name') as $roles)
                               @if($roles== $permission->name)
                               checked="checked"
                            @endif
                            @endforeach
                        > {{$permission->name}}
                        <span></span>
                    </label>
                @else
                    <label class="kt-checkbox">
                        <input type="checkbox"name="permissions[]" value="{{$permission->name}}"
                        > {{$permission->name}}
                        <span></span>
                    </label>
                @endif
            @empty
                <div class="checkbox">
                    <label>
                        No Permission
                    </label>
                </div>
            @endforelse
        </div>
    </div>
</form>

resources/views/app/pages/roles/_scripts.blade.php
<script>
    var btn;
    var modal;
    var form;
    $(document).ready(function(){
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        $('#roles-datatable').DataTable({
            processing: true,
            serverSide: true,
            responsive: true,

            ajax:{
                "url": '{!! route("roles.datatable") !!}',
                "type": "GET",
            },
            columns: [
                { data: 'name', name: 'name' },
                { data: 'permissions', name: 'permissions' },
                { data: 'created_at', name: 'created_at'},
                { data: 'action', name: 'action',searchable:false,orderable:false},

            ],
            columnDefs:[
                {targets:3,"width":"10%"}
            ],
            "order": [[ 0, "asc" ]], //or asc
        });

    });

    /*render create-edit modal*/
    $('#modal-lg').on('show.bs.modal', function (event) {
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        var button = $(event.relatedTarget); // Button that triggered the modal
        btn = button.data('btn'); // Extract info from data-* attributes
        modal = $(this);
        modal.find('.btn-modal-submit').css('display','');
        form = modal.find(".modal-body #form");
        form.trigger('reset');
        if (btn === 'create') {
            var url = '{{ route("roles.create")}}';
            $.ajax({
                url: url, //this is your uri
                type: 'get', //this is your method
                dataType: 'json',
                success: function (response) {
                    //console.log(response.form);
                    modal.find('.modal-title').html('CREATE ROLE');
                    modal.find('.modal-body').html(response.form);
                    form = modal.find(".modal-body #form");
                    // $('input.flat').iCheck({
                    //     checkboxClass: 'icheckbox_flat-green',
                    //     radioClass: 'iradio_flat-green'
                    // });
                    form.attr('action', '{{ route("roles.store")}}');
                    form.attr('method', 'POST');
                    modal.find('.btn-modal-submit').html('Save');
                }
            })//end ajax
        } else if (btn === 'edit') {
            var role_id = button.data('id');
            var url = '{{ route("roles.edit",":role_id")}}';
            url = url.replace(':role_id', role_id);
            $.ajax({
                url: url, //this is your uri
                type: 'get', //this is your method
                dataType: 'json',
                success: function (response) {
                    //console.log(response.form);
                    var url = '{{ route("roles.update",":role_id")}}';
                    url = url.replace(':role_id', role_id);
                    modal.find('.modal-title').html('EDIT ROLE');
                    modal.find('.modal-body').html(response.form);
                    form = modal.find(".modal-body #form");
                    // form.find('input.flat').iCheck({
                    //     checkboxClass: 'icheckbox_flat-green',
                    //     radioClass: 'iradio_flat-green'
                    // });
                    form.attr('action', url);
                    form.attr('method', 'POST');
                    modal.find('.btn-modal-submit').html('Update');
                }
            })//end ajax
        }
    });

    $('#modal-lg-delete').on('show.bs.modal', function (event) {
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
        var button = $(event.relatedTarget); // Button that triggered the modal
        var role_id = button.data('id');// Extract info from data-* attributes
        var url = '{{ route("roles.destroy", ":role_id") }}';
       // modal.find('.btn-modal-submit').css('display','');
        btn = button.data('btn');
        url = url.replace(':role_id', role_id);
        modal = $(this);
        form = modal.find('.modal-body #form-delete');
        console.log(form);
        form.attr('action', url);
        console.log(form.attr('action', url));
        modal.find('.modal-title').html('DELETE ROLE');
        modal.find('.btn-modal-submit').html('Delete');
        modal.find('.modal-body #message').html(' <strong>Role will be DELETED!</strong> Are you sure to process this transaction?');
    });

    /*AJAX SUBMIT*/
    $(".btn-modal-submit").click(function (e) {
        e.preventDefault(); // avoid to execute the actual submit of the form.
        var url =  form.attr('action');
        console.log(url);
        $.ajax({
            type: form.attr('method'),
            url: url,
            data: form.serialize(), // serializes the form's elements.
            success: function (data) {

                checkValidation(form,data);

                $('#roles-datatable').DataTable().ajax.reload();
                if(btn !== 'delete'){
                    modal.find('.modal-body #name').val(data.name)
                }

                if(btn === 'edit'){

                    modal.find('.modal-body').html('');
                    setTimeout(function() {
                        modal.find('.modal-footer').css('display','');
                        modal.modal('toggle');

                    }, 1500);
                    modal.find('.modal-footer').css('display','none');
                }

            }, error: function (xhr, ajaxOptions, thrownError) {
                checkValidation(form,xhr);
                //modal.find('.modal-footer').css('display','none');
            }
        });
    });

    /*functions*/

    function checkValidation(form,data){
        if(data.status==='success'){
            var success = modal.find('.success-modal');
            success.fadeIn();
            success.html(data.message);
            success.css('display','');
            form.trigger("reset");
            // if(btn==='create'){
            //     form.find('input.flat').iCheck('update');
            // }

            if(btn==='delete'){
                modal.find('.btn-modal-submit').css('display','none');
            }
            success.delay(800).fadeOut(300, function(){
                success.css('display','none');
                if(btn==='delete'){
                    modal.modal('toggle');
                }
            });
        }else{
            var error = modal.find('.error-modal');
            var message = '';
            $.each(data.responseJSON.errors, function (key, value) {
                message += ' '+value
            });
            console.log(message);
            error.fadeIn();
            error.html(message);
            error.css('display','');
            error.delay(800).fadeOut(300, function(){
                error.css('display','none');
            })
        }
    }


</script>

resources/views/app/pages/roles/index.blade.php
@extends("app.layout.app")
@section("title","Role")
@push('page-vendors')
    <link href="./assets/vendors/custom/datatables/datatables.bundle.css" rel="stylesheet" type="text/css" />
@endpush
@push("page-styles")
    <link href="./assets/vendors/general/tether/dist/css/tether.css" rel="stylesheet" type="text/css" />
    <link href="./assets/vendors/general/bootstrap-datepicker/dist/css/bootstrap-datepicker3.css" rel="stylesheet" type="text/css" />
    <link href="./assets/vendors/general/bootstrap-datetime-picker/css/bootstrap-datetimepicker.css" rel="stylesheet" type="text/css" />
    <link href="./assets/vendors/general/bootstrap-timepicker/css/bootstrap-timepicker.css" rel="stylesheet" type="text/css" />
    <link href="./assets/vendors/general/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet" type="text/css" />
    <link href="./assets/vendors/general/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.css" rel="stylesheet" type="text/css" />
    <link href="./assets/vendors/general/bootstrap-select/dist/css/bootstrap-select.css" rel="stylesheet" type="text/css" />
    <link href="./assets/vendors/general/bootstrap-switch/dist/css/bootstrap3/bootstrap-switch.css" rel="stylesheet" type="text/css" />
    <link href="./assets/vendors/general/select2/dist/css/select2.css" rel="stylesheet" type="text/css" />
    <link href="./assets/vendors/general/ion-rangeslider/css/ion.rangeSlider.css" rel="stylesheet" type="text/css" />
    <link href="./assets/vendors/general/nouislider/distribute/nouislider.css" rel="stylesheet" type="text/css" />
    <link href="./assets/vendors/general/owl.carousel/dist/assets/owl.carousel.css" rel="stylesheet" type="text/css" />
    <link href="./assets/vendors/general/owl.carousel/dist/assets/owl.theme.default.css" rel="stylesheet" type="text/css" />
    <link href="./assets/vendors/general/dropzone/dist/dropzone.css" rel="stylesheet" type="text/css" />
    <link href="./assets/vendors/general/summernote/dist/summernote.css" rel="stylesheet" type="text/css" />
    <link href="./assets/vendors/general/bootstrap-markdown/css/bootstrap-markdown.min.css" rel="stylesheet" type="text/css" />
    <link href="./assets/vendors/general/animate.css/animate.css" rel="stylesheet" type="text/css" />
    <link href="./assets/vendors/general/toastr/build/toastr.css" rel="stylesheet" type="text/css" />
    <link href="./assets/vendors/general/morris.js/morris.css" rel="stylesheet" type="text/css" />
    <link href="./assets/vendors/general/sweetalert2/dist/sweetalert2.css" rel="stylesheet" type="text/css" />
    <link href="./assets/vendors/general/socicon/css/socicon.css" rel="stylesheet" type="text/css" />
    <link href="./assets/vendors/custom/vendors/line-awesome/css/line-awesome.css" rel="stylesheet" type="text/css" />
    <link href="./assets/vendors/custom/vendors/flaticon/flaticon.css" rel="stylesheet" type="text/css" />
    <link href="./assets/vendors/custom/vendors/flaticon2/flaticon.css" rel="stylesheet" type="text/css" />
    <link href="./assets/vendors/general/@fortawesome/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css" />
@endpush
@section("content")
    <!-- begin:: Content Head -->
    <div class="kt-subheader   kt-grid__item" id="kt_subheader">
        <div class="kt-subheader__main">
            <h3 class="kt-subheader__title">Role</h3>

        </div>
    </div>
    <div class="kt-content  kt-grid__item kt-grid__item--fluid" id="kt_content">

        <div class="kt-portlet kt-portlet--mobile">
            <div class="kt-portlet__head kt-portlet__head--lg">
                <div class="kt-portlet__head-label">
										<span class="kt-portlet__head-icon">
											<i class="kt-font-brand flaticon2-user-1"></i>
										</span>
                    <h3 class="kt-portlet__head-title">
                        Roles Data
                    </h3>
                </div>
                <div class="kt-portlet__head-toolbar">
                    <div class="kt-portlet__head-wrapper">
                        <div class="kt-portlet__head-actions">

                            <a href="#" class="btn btn-brand btn-elevate btn-icon-sm"  data-btn="create" data-toggle="modal" data-target="#modal-lg">
                                <i class="la la-plus"></i>
                                New Role
                            </a>

                        </div>
                    </div>
                </div>
            </div>

            <div class="kt-portlet__body">
                <!--begin: Datatable -->
                <table class="table table-bordered  table-checkable" id="roles-datatable">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Permissions</th>
                        <th>Created At</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                    </tr>
                    </tbody>
                </table>
                <!--end: Datatable -->
            </div>
        </div>
    </div>
    <!-- end:: Content Head -->




@endsection
@push("page-scripts")
    <script src="./assets/vendors/general/jquery-form/dist/jquery.form.min.js" type="text/javascript"></script>
    <script src="./assets/vendors/general/block-ui/jquery.blockUI.js" type="text/javascript"></script>
    <script src="./assets/vendors/general/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js" type="text/javascript"></script>
    <script src="./assets/vendors/custom/js/vendors/bootstrap-datepicker.init.js" type="text/javascript"></script>
    <script src="./assets/vendors/general/bootstrap-datetime-picker/js/bootstrap-datetimepicker.min.js" type="text/javascript"></script>
    <script src="./assets/vendors/general/bootstrap-timepicker/js/bootstrap-timepicker.min.js" type="text/javascript"></script>
    <script src="./assets/vendors/custom/js/vendors/bootstrap-timepicker.init.js" type="text/javascript"></script>
    <script src="./assets/vendors/general/bootstrap-daterangepicker/daterangepicker.js" type="text/javascript"></script>
    <script src="./assets/vendors/general/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.js" type="text/javascript"></script>
    <script src="./assets/vendors/general/bootstrap-maxlength/src/bootstrap-maxlength.js" type="text/javascript"></script>
    <script src="./assets/vendors/custom/vendors/bootstrap-multiselectsplitter/bootstrap-multiselectsplitter.min.js" type="text/javascript"></script>
    <script src="./assets/vendors/general/bootstrap-select/dist/js/bootstrap-select.js" type="text/javascript"></script>
    <script src="./assets/vendors/general/bootstrap-switch/dist/js/bootstrap-switch.js" type="text/javascript"></script>
    <script src="./assets/vendors/custom/js/vendors/bootstrap-switch.init.js" type="text/javascript"></script>
    <script src="./assets/vendors/general/select2/dist/js/select2.full.js" type="text/javascript"></script>
    <script src="./assets/vendors/general/ion-rangeslider/js/ion.rangeSlider.js" type="text/javascript"></script>
    <script src="./assets/vendors/general/typeahead.js/dist/typeahead.bundle.js" type="text/javascript"></script>
    <script src="./assets/vendors/general/handlebars/dist/handlebars.js" type="text/javascript"></script>
    <script src="./assets/vendors/general/inputmask/dist/jquery.inputmask.bundle.js" type="text/javascript"></script>
    <script src="./assets/vendors/general/inputmask/dist/inputmask/inputmask.date.extensions.js" type="text/javascript"></script>
    <script src="./assets/vendors/general/inputmask/dist/inputmask/inputmask.numeric.extensions.js" type="text/javascript"></script>
    <script src="./assets/vendors/general/nouislider/distribute/nouislider.js" type="text/javascript"></script>
    <script src="./assets/vendors/general/owl.carousel/dist/owl.carousel.js" type="text/javascript"></script>
    <script src="./assets/vendors/general/autosize/dist/autosize.js" type="text/javascript"></script>
    <script src="./assets/vendors/general/clipboard/dist/clipboard.min.js" type="text/javascript"></script>
    <script src="./assets/vendors/general/dropzone/dist/dropzone.js" type="text/javascript"></script>
    <script src="./assets/vendors/general/summernote/dist/summernote.js" type="text/javascript"></script>
    <script src="./assets/vendors/general/markdown/lib/markdown.js" type="text/javascript"></script>
    <script src="./assets/vendors/general/bootstrap-markdown/js/bootstrap-markdown.js" type="text/javascript"></script>
    <script src="./assets/vendors/custom/js/vendors/bootstrap-markdown.init.js" type="text/javascript"></script>
    <script src="./assets/vendors/general/bootstrap-notify/bootstrap-notify.min.js" type="text/javascript"></script>
    <script src="./assets/vendors/custom/js/vendors/bootstrap-notify.init.js" type="text/javascript"></script>
    <script src="./assets/vendors/general/jquery-validation/dist/jquery.validate.js" type="text/javascript"></script>
    <script src="./assets/vendors/general/jquery-validation/dist/additional-methods.js" type="text/javascript"></script>
    <script src="./assets/vendors/custom/js/vendors/jquery-validation.init.js" type="text/javascript"></script>
    <script src="./assets/vendors/general/toastr/build/toastr.min.js" type="text/javascript"></script>
    <script src="./assets/vendors/general/raphael/raphael.js" type="text/javascript"></script>
    <script src="./assets/vendors/general/morris.js/morris.js" type="text/javascript"></script>
    <script src="./assets/vendors/general/chart.js/dist/Chart.bundle.js" type="text/javascript"></script>
    <script src="./assets/vendors/custom/vendors/bootstrap-session-timeout/dist/bootstrap-session-timeout.min.js" type="text/javascript"></script>
    <script src="./assets/vendors/custom/vendors/jquery-idletimer/idle-timer.min.js" type="text/javascript"></script>
    <script src="./assets/vendors/general/waypoints/lib/jquery.waypoints.js" type="text/javascript"></script>
    <script src="./assets/vendors/general/counterup/jquery.counterup.js" type="text/javascript"></script>
    <script src="./assets/vendors/general/es6-promise-polyfill/promise.min.js" type="text/javascript"></script>
    <script src="./assets/vendors/general/sweetalert2/dist/sweetalert2.min.js" type="text/javascript"></script>
    <script src="./assets/vendors/custom/js/vendors/sweetalert2.init.js" type="text/javascript"></script>
    <script src="./assets/vendors/general/jquery.repeater/src/lib.js" type="text/javascript"></script>
    <script src="./assets/vendors/general/jquery.repeater/src/jquery.input.js" type="text/javascript"></script>
    <script src="./assets/vendors/general/jquery.repeater/src/repeater.js" type="text/javascript"></script>
    <script src="./assets/vendors/general/dompurify/dist/purify.js" type="text/javascript"></script>

@endpush
@push("scripts")
    <script src="./assets/vendors/custom/datatables/datatables.bundle.js" type="text/javascript"></script>
    <script src="./assets/js/demo1/pages/crud/datatables/basic/paginations.js" type="text/javascript"></script>

    @include('app.pages.roles._scripts')
@endpush